# Generated by Django 6.1 on 2026-08-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('status_code', models.IntegerField()),
                ('title', models.TextField(blank=True, null=True)),
                ('headings', models.JSONField(default=list)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
