# Generated by Django 6.1 on 2026-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='links',
            field=models.JSONField(default=list),
        ),
    ]
