# Generated by Django 6.1 on 2026-09-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_page_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='incoming_links',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
