# Generated by Django 6.1 on 2026-09-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_page_incoming_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='incoming_links',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
