# Generated by Django 6.1 on 2026-09-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_page_incoming_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_crawled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
