# Generated by Django 6.1 on 2026-09-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_indexentry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='indexentry',
            constraint=models.UniqueConstraint(fields=('word', 'page'), name='unique_word_page'),
        ),
    ]
