# Generated by Django 6.1.1 on 2026-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_indexentry_unique_word_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
